name: Test Installer

on:
  push:
    branches:
      - main

jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
         

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: pyinstaller --onefile  --hidden-import=encodings  osdag_script.py

      - name: List Files in Dist Directory
        run: dir dist

      - name: Check system info
        run: |
          systeminfo
          echo "Current directory: $(pwd)"

      - name: Run the Executable
        run: |
          Set-Location -Path "D:\a\Osdag-Task\Osdag-Task"
          dir .\dist
          & ".\dist\osdag_script.exe"

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: osdag_installer
          path: dist/osdag_script.exe
